// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl-7ud8BAiLW_AzA9k8xEnPx7TpnupOwM',
    appId: '1:1070998759706:web:c43c82af047cf257cfa4a3',
    messagingSenderId: '1070998759706',
    projectId: 'itidayone',
    authDomain: 'itidayone.firebaseapp.com',
    storageBucket: 'itidayone.firebasestorage.app',
    measurementId: 'G-SH286D1W6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB25sGqBDC2E6qDDqcHOO0MgaEVm-_hgM',
    appId: '1:1070998759706:android:945849abb5ef91d9cfa4a3',
    messagingSenderId: '1070998759706',
    projectId: 'itidayone',
    storageBucket: 'itidayone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjPqS0PNsc3LfEiAFxzO91hvkGGNJVpTs',
    appId: '1:1070998759706:ios:e015ef1097ae1f90cfa4a3',
    messagingSenderId: '1070998759706',
    projectId: 'itidayone',
    storageBucket: 'itidayone.firebasestorage.app',
    iosBundleId: 'com.example.firebasedayone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjPqS0PNsc3LfEiAFxzO91hvkGGNJVpTs',
    appId: '1:1070998759706:ios:e015ef1097ae1f90cfa4a3',
    messagingSenderId: '1070998759706',
    projectId: 'itidayone',
    storageBucket: 'itidayone.firebasestorage.app',
    iosBundleId: 'com.example.firebasedayone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl-7ud8BAiLW_AzA9k8xEnPx7TpnupOwM',
    appId: '1:1070998759706:web:f4e8ba8eefec7ad5cfa4a3',
    messagingSenderId: '1070998759706',
    projectId: 'itidayone',
    authDomain: 'itidayone.firebaseapp.com',
    storageBucket: 'itidayone.firebasestorage.app',
    measurementId: 'G-XPQDDVMG6E',
  );
}
